default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: cookie_practice_development

test:
  <<: *default
  database: cookie_practice_test

production:
  <<: *default
  database: cookie_practice_production
  url: <%= ENV["DB_URL"] %>